version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"  # Jupyter Notebook/Lab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
